disabled_rules:
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity

identifier_name:
  min_length: 2 # restrict short names like i, x, p, but allow names like id
  allowed_symbols: ['_']
  excluded:
    - extension_

line_length:
  warning: 150
  error: 160

file_length:
  warning: 2500
  error: 3500

type_body_length:
  warning: 2500
  error: 3000

function_body_length:
  warning: 300
  error: 500
