disabled_rules:
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - line_length
  - multiple_closures_with_trailing_closure
  - switch_case_alignment
  - unused_optional_binding
  - cyclomatic_complexity
  - static_over_final_class

# Optional: Customize length limits instead of disabling
# identifier_name:
#   min_length: 1 # allow short names like i, x, p
#   allowed_symbols: ['_']
#   excluded:
#     - i
#     - a
#     - b
#     - p
#     - extension_

# line_length:
#   warning: 200
#   error: 250

# file_length:
#   warning: 1000
#   error: 1500

# type_body_length:
#   warning: 1000
#   error: 1500

# function_body_length:
#   warning: 100
#   error: 200
