name: 1. SwiftLint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint
