name: 1. SwiftLint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Run SwiftLint
    runs-on:
      - thevickypedia-default
      - macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          if [[ ! $(command -v swiftlint) ]]; then
            echo "SwiftLint not found. Installing..."
            brew install swiftlint
          fi
          echo "::notice title=Swiftlint Version::$(swiftlint --version)"
        shell: bash

      - name: Run SwiftLint
        run: swiftlint
